create_clock -name clk -period 2 -waveform {0 1} [get_ports "clk"] 
set_clock_transition -rise 0.1 [get_clocks "clk"] 
set_clock_transition -fall 0.1 [get_clocks "clk"] 
set_clock_uncertainty -rise 0.01 [get_clocks "clk"] 
set_clock_uncertainty -fall 0.01 [get_clocks "clk"] 
set_input_delay -max 1.0 -clock [get_clocks "clk"] [get_ports "data_in[*]"] 
set_input_delay -max 1.0 -clock [get_clocks "clk"] [get_ports "shift[*]"] 
set_input_delay -max 1.0 -clock [get_clocks "clk"] [get_ports "mode[*]"] 
set_input_delay -max 1.0 -clock [get_clocks "clk"] [get_ports "rot_dir"]                      
set_output_delay -max 1.0 -clock [get_clocks "clk"] [get_ports "data_out[*]"] 
set_false_path -from [get_ports "rst"]
